import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface ExportData {
    formData: any;
    result: any;
    insights: string[];
    recommendations: string[];
}

export function exportPredictionPdf({
    formData,
    result,
    insights,
    recommendations,
}: ExportData) {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(20);
    doc.text("Customer Churn Prediction Report", 14, 18);

    doc.setFontSize(10);
    doc.setTextColor(120);

    doc.text(
        `Generated: ${new Date().toLocaleString()}`,
        14,
        25
    );

    // Prediction
    doc.setTextColor(0);
    doc.setFontSize(14);

    doc.text("Prediction Summary", 14, 40);

    autoTable(doc, {
        startY: 45,
        head: [["Field", "Value"]],
        body: [
            ["Prediction", result.prediction_label],
            [
                "Probability",
                `${(result.probability.churn * 100).toFixed(2)}%`,
            ],
        ],
        theme: "grid",
    });

    // Customer
    autoTable(doc, {
        startY: (doc as any).lastAutoTable.finalY + 10,
        head: [["Customer Information", "Value"]],
        body: [
            ["Gender", formData.gender],
            ["Senior Citizen", formData.SeniorCitizen ? "Yes" : "No"],
            ["Partner", formData.Partner],
            ["Dependents", formData.Dependents],
            ["Phone Service", formData.PhoneService],
            ["Internet Service", formData.InternetService],
            ["Contract", formData.Contract],
            ["Payment Method", formData.PaymentMethod],
            ["Tenure", `${formData.tenure} Months`],
            ["Monthly Charges", `$${Number(formData.MonthlyCharges).toFixed(2)}`],
            ["Total Charges", `$${Number(formData.TotalCharges).toFixed(2)}`],
        ],
        theme: "striped",
    });

    // AI Insight
    let y = (doc as any).lastAutoTable.finalY + 12;

    doc.setFontSize(14);
    doc.text("AI Insight", 14, y);

    y += 8;

    doc.setFontSize(11);

    insights.forEach((item) => {
        doc.text(`• ${item}`, 18, y);
        y += 7;
    });

    y += 5;

    doc.setFontSize(14);
    doc.text("Recommendations", 14, y);

    y += 8;

    doc.setFontSize(11);

    recommendations.forEach((item) => {
        doc.text(`• ${item}`, 18, y);
        y += 7;
    });

    doc.setDrawColor(180);
    doc.line(14, 280, 196, 280);

    doc.setFontSize(10);
    doc.setTextColor(120);

    doc.text(
        "Generated by Customer Churn AI Analytics Platform",
        14,
        287
    );

    doc.save(
        `customer-churn-report-${Date.now()}.pdf`
    );
}